site_name: MDM Docs
site_url: https://mdmdocs.tripleu.org

docs_dir: docs
site_dir: site

theme:
  name: mkdocs

nav:
  - Home: index.md
  - Android app: android-app.md
  - Website: website.md
  - Firestore config: firestore-config.md
  - VPN (WireGuard): vpn-wireguard.md
  - MITM proxy: mitm-proxy.md
  - Directus: directus.md
